### ISSUE TITLE
numberformatexception on new

### ISSUE THREAD

**Issue by maxandersen** [adoble/adr-j#43]
when I try this I get: 

```
adr new wiki migration
java.lang.NumberFormatException: For input string: "imag"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.<init>(Integer.java:1127)
	at org.doble.commands.CommandNew.toInt(CommandNew.java:264)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:520)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:483)
	at org.doble.commands.CommandNew.highestIndex(CommandNew.java:251)
	at org.doble.commands.CommandNew.call(CommandNew.java:133)
	at org.doble.commands.CommandNew.call(CommandNew.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.doble.adr.ADR.run(ADR.java:99)
	at org.doble.adr.ADR.main(ADR.java:72)
```

**Comment by adoble** [comment]
I haven't looked at this project for sometime now and I suspect that the code is not in step with newer versions of java and other dependencies. 

I won't be able to look at it immediately, but what version of Java are you using?

**Comment by maxandersen** [comment]
17

**Comment by adoble** [comment]
I've had a more detailed look at this. I suspect that in the  directory where you have the ADRs (default is `doc/adr`) you have a file or directory whose name starts with "imag" rather that an ADR number such as 0003. 

Workaround is  to remove any files/directories form the `doc/adr` directory that haven't been generated with `adr` and therefore don't have the "correct" format.

I realize that this is a sub-optional solution. In hindsight, it seems to be a reasonable use case for users to create other objects in the `doc/adr` directory (for instance, a directory called `images` ). 

Two proposals: 

1. Change the code so that non-conforming objects in the `doc/adr` directory are simply ignored. 
2. Change the code so that  non-conforming objects in the `doc/adr`  directory  cause a warning to be printed. 

I tend towards 1.

**Comment by adoble** [comment]
Fixed by  allowing a user to add other files and directories in the same directory as the ADRs. The behavior is now that files and directories that are not "well formed" ADRs are ignored.
