### ISSUE TITLE
init after config does now work correctly

### ISSUE THREAD

**Issue by sdavids** [adoble/adr-j#51]
```shell
$ mkdir /tmp/test && cd "$_"
$ adr config dateFormat ISO_LOCAL_DATE
$ ls -A
.adr
$ adr init
Directory is already initialised for ADR.
$ adr new test
org.doble.adr.ADRException: FATAL: Unable to determine the indexes of the ADRs.
        at org.doble.commands.CommandNew.highestIndex(CommandNew.java:251)
        at org.doble.commands.CommandNew.call(CommandNew.java:132)
        at org.doble.commands.CommandNew.call(CommandNew.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.doble.adr.ADR.run(ADR.java:89)
        at org.doble.adr.ADR.main(ADR.java:65)
Caused by: java.nio.file.NoSuchFileException: /private/tmp/test/doc/adr
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:461)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:481)
        at java.base/java.nio.file.Files.list(Files.java:3772)
        at org.doble.commands.CommandNew.highestIndex(CommandNew.java:248)
        ... 12 more
```

**Comment by adoble** [comment]
Thanks for spotting this and correcting it with the PRs. Should now work in release 3.3.0.
