### ISSUE TITLE
Unhandled exception with adr config author

### ISSUE THREAD

**Issue by adoble** [adoble/adr-j#61]
Configuring an author without any name gives an exception:

```console
# adr-dev config author
java.lang.NullPointerException: Cannot read the array length because "<local4>" is null
        at org.doble.commands.CommandConfig.author(CommandConfig.java:66)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2070)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.doble.adr.ADR.run(ADR.java:89)
        at org.doble.adr.ADR.main(ADR.java:65)
```

**Comment by adoble** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 61](https://trello.com/c/EA5XpwLw/171-issue-61)
